### ISSUE TITLE
Amp sims (GrindAmp, FireAmp, LeadAmp, LilAmp, MidAmp, BigAmp, Cabs, Golem)

### ISSUE THREAD

**Issue by fpesari** [hannesbraun/airwindows-lv2#10]
Hello,

despite the wide availability of such libre plugins (Guitarix, Rakarrack, GuitarML, Kapitonov plugins and more!), amp sims still belong to a very requested category of plugins (it may be because of guitarist culture!) and I've heard from an experienced guitarist that the AirWindows ones are good. You already did `XRegion`, could you please port the others: GrindAmp, FireAmp, LeadAmp, LilAmp, MidAmp, BigAmp, Cabs, Golem ? 

Thank you.

PS: I opened many issues not to overload you with requests (you can do them if and when you want :smiley:) but just because I had the chance to read a bit the [Airwindopedia](https://www.airwindows.com/wp-content/uploads/Airwindopedia.txt). So I apologize if your emails got spammed with my posts and above all, thank you again for all your patience and much useful work!

**Comment by hannesbraun** [comment]
I had a few minutes today to port Golem: fd13bc738eef7ef795ce632df27033e7ddcf0f54

**Comment by SpotlightKid** [comment]
I'll second that and also humbly request the addition of BassAmp, BassDrive and BassKit, if possible.

**Comment by hannesbraun** [comment]
A little bit of progress: GrindAmp and Cabs got ported over the weekend (8b9a7e631d8584c580168e6d0b78f1c1aed49507 and 3b6623369b38f88dfea5ede7c8df302694be8d54)

> and also humbly request the addition of BassAmp, BassDrive and BassKit, if possible

Done: 66dd837c7945559c1df466aba2c41b9a81c7fffc, 43478aa16b9baf82cf6d181cd5a73565a1942bff and d571f3f4751fb7b15abbb4952072ee1152c53585

**Comment by hannesbraun** [comment]
Finally, I ported all of your requested plugins :)

**Comment by fpesari** [comment]
> Finally, I ported all of your requested plugins :)

Wow, that's awesome Hannes, thank you!

**Comment by SpotlightKid** [comment]
Awesome. Thank you very much.

Can you please tag a new release?

**Comment by hannesbraun** [comment]
> Can you please tag a new release?

Version 26.0 is now released.
