### ISSUE TITLE
No GUI showing up in Carla under Wayland

### ISSUE THREAD

**Issue by felixniemeyer** [hannesbraun/airwindows-lv2#15]
Hey there, 
I found the "Galactic" reverb on [https://patchstorage.com/galactic/](https://patchstorage.com/galactic/) and I'm trying to use it in Carla. 
When I click on "show custom gui" nothing happens and I suppose that might be related to the fact I am using wayland instead of X11 on my system. 
Maybe it's also a Carla thing though there are no hints in the terminal output of Carla. 
Any ideas?
Thank you!

**Comment by hannesbraun** [comment]
I did not develop that GUI. I could try to guess what's going wrong. But I don't use Carla, nor did I ever use the GUI version. Unfortunately, the author of the GUI seems to be linking to this repository. So I can't really help you there. Try to find out who  *really* developed the GUI and ask him about the issue. Sorry!
