### ISSUE TITLE
ToTape5

### ISSUE THREAD

**Issue by fpesari** [hannesbraun/airwindows-lv2#16]
Hello Hannes,

how are you doing? I know you already made ToTape6 but I've hard ToTape5 is pretty different (some people prefer it) and so I ask for its inclusion. Thanks!

**Comment by hannesbraun** [comment]
Hi Fabio,

I'm busy as always but I'm doing well 😀. I hope you're doing good as well.

I'm not at home right now, but I'll probably find the time to port ToTape5 later this evening when I'll get home again.

By the way, #10 is taking a bit that long as it's taking a lot of time to verify the correctness of each of those plugins. But at some point, I'll get them done :D

**Comment by hannesbraun** [comment]
Done: a618a564a1aaa1355403f191806ff33b7c74b5c6

**Comment by fpesari** [comment]
Everything fine here, too, thanks. That was fast! Thank you for your commitment and also for the work on the other larger ticket, it's much appreciated :)
