### ISSUE TITLE
Plugins request

### ISSUE THREAD

**Issue by gechoto** [hannesbraun/airwindows-lv2#17]
Hi Hannes, thanks for the plugins so far.
Please consider also porting the following:
- Doublelay
- Air2
- Air3

**Comment by hannesbraun** [comment]
Air2 and Air3 have just been released in version 30.0.

My ported version of Doublelay still has some issues (and I don't know why), so I didn't publish it yet.

**Comment by hannesbraun** [comment]
Doublelay is now also ported with 065ff4cbcb8ddaa8fa99f337f46f749adf11b973 and will be included in the next release.
