### ISSUE TITLE
PhaseNudge

### ISSUE THREAD

**Issue by fpesari** [hannesbraun/airwindows-lv2#4]
Hello Hannes,

could you please port PhaseNudge to LV2? It's a critical plugin because I don't think there are many libre all-pass rotator LV2 plugins (except one from SWH). Thanks!

**Comment by hannesbraun** [comment]
Done :)
See 75adf7f37fd1eb12a2668e2e79b1c81393ce7c6c

I can make a release later this day. It might take me some time though to adjust the OBS build for the new Meson build system... depends on me :D

**Comment by fpesari** [comment]
Wow, that was quick, thanks! There are RPM macros for Meson too, so I hope that won't be a problem :smile_cat:
