### ISSUE TITLE
[Feature Request] Document the Process

### ISSUE THREAD

**Issue by frink** [hannesbraun/airwindows-lv2#5]
Since Chris has done so many plugins and he still releases one almost every week, it would be good to crowd-source the conversion of these plugins to LV2. In order to do that we need documentation on the conversion process so that anyone can come to this repo and do a PR. Also, it is very likely that if we have a PR process we can automate the conversion. Plus, if we can tell Chris what we are doing it is highly likely he will end up including LV2 as a target along with his existing targets...

All that requires good concise documentation. This can be either in the form of videos walking through the conversion process and/or documentation with step by step directions. Does not have to be extensive. Just enough for a "qualified developer" to read and follow.

This is an amazing project and I'd love to see it grow!

**Comment by hannesbraun** [comment]
I extended the README a bit to include some installation instructions. I also wrote a "CONTRIBUTING.md` that documents the process of porting a plugin.

Both documents are available on the dev branch. Is that what you were looking for? If so, feel free to close this issue. Otherwise, let me know what you're still missing.

I'm not really confident about making a video though... at least if I don't have to ;) If this is a strong requirement, let me know.

By the way, I automated the release process today. Pre-built binaries for all major platforms will be available with the next release through GitHub Releases. Nightly builds are available though the artifacts of a GitHub Actions build. This should make this port more accessible for non-developers... hopefully

**Comment by frink** [comment]
No need for video. The text files are more than adequate.

The README additions look great.

The CONTRIBUTING file needs a few clarifications but overall looks good too.

Thank you very much for a prompt reply.

----

Congrats on the CI/CD automation! That's WONDERFUL!!!

I'd love to see Chris adopt more automation in his repo. Right now he has essentially 6 separate code bases. If he eventually includes [CLAP](https://github.com/baconpaul/airwin2clap) and LV2 that's eight code bases. He needs to move to a wrapper based environment to continue supporting new formats. It would be great if we could get everything unified in one code base with many wrappers. But this intermediary work is necessary to understand those complexities. And distilling to ANSI C is a wise move to simplify life in that process. [DPF](https://github.com/DISTRHO/DPF) may be the eventual solution once they incorporate AU and CLAP next year. _(Especially if we can get a better UI as part of the deal...)_

----

Comments on the CONTRIBUTING file:

> Find the plugin to port in the MacVST directory

There should probably be some explanation as to why we should use the MacVST variant when porting. I'm genuinely curious and I'm sure anyone else reading would be too. But there may be some knowledge transfer that could be helpful to other ports too. Also, explaining why using C instead of C++ would be useful. (Personally, like C but most audio stuff is in C++...)

> Also, parameters whose sliders don't map linearly to their values due to extra code added (usually in <PluginName>.cpp) should be adjusted to have a linear mapping. (If there will be an option built into LV2 to do this properly, this might be an option for the future.)

It would be good to cite an example for this. BussColors4 would be the perfect example if it were ported.

> Values ranging from 0 to 1 usually don't have a unit. Otherwise, choose the appropriate unit. If it is not available, create it yourself. There is an example of this in IronOxideClassic2.

This should link to the example for clarity's sake. (Assume you're talking about [IPS](https://github.com/hannesbraun/airwindows-lv2/blob/3a5bf938c44ff2cfef0727da83a1515ac77d8f0e/src/IronOxideClassic2/IronOxideClassic2.ttl#L65)...)

> Copy the state variables from the original <PluginName>.h to the plugin struct. There are some VST specific variables in there that don't need to be copied.

Someone unfamiliar with VST coding will not know what is VST specific. Probably need to spell out what to look for...

> Also, remember that you don't need to copy the variables named A, B and so on, as you should have already added those (with a better name that corresponds to their port name).

Might want to put this on its own line or highlight it in some way. My eyes jumped and missed it the first time through.

> Now, it's time for a null test...

This paragraph and the following should probably have the same bullet structure as you use above so that the file can be treated like a checklist across the board. I would also suggest adding sections headings similar to the README for usability.

The rest is golden!!!

----

Again thanks for adding this documentation as it helps spread the load to the community.

I'm likely to start contributing regularly once I've got my music system reconfigured in the next few weeks.

**Comment by hannesbraun** [comment]
Thanks for your feedback. I adjusted the CONTRIBUTING file accordingly.
