### ISSUE TITLE
Plugins request: Distance2, DrumSlam, Monitoring

### ISSUE THREAD

**Issue by fpesari** [hannesbraun/airwindows-lv2#6]
Hello Hannes,

I asked around on an Italian Telegram audio production group what are their favorite Airwindows plugins and the answers I got so far are:
- Distance2
- DrumSlam
- Monitoring

Since you asked to open an issue for plugin requests, here they are :smile: of course, no rush! And as always, thank you for your work.

**Comment by hannesbraun** [comment]
Cool, thanks for letting me know. ...aaaand the plugins just got ported to LV2. [Version 12.0](https://github.com/hannesbraun/airwindows-lv2/releases/tag/v12.0) is released ;)

**Comment by fpesari** [comment]
Wow, so fast! Thank you, much appreciated.
