### ISSUE TITLE
GlitchShifter and PitchNasty

### ISSUE THREAD

**Issue by fpesari** [hannesbraun/airwindows-lv2#9]
Hello,

I went through the [Airwindopedia](https://www.airwindows.com/wp-content/uploads/Airwindopedia.txt) and it seems that there are two nice pitch shifters which could be useful to have in lv2 format: GlitchShifter and PitchNasty. Could you please port them? Thank you!

**Comment by hannesbraun** [comment]
PitchNasty got ported: 40f4497f

**Comment by hannesbraun** [comment]
GlitchShifter got ported as well: 40b11a89b0173572a06c8f8b0b7569352ac0fd3a
